# Generated by Django 4.2.16 on 2024-12-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_osoba_options_alter_stanowisko_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default='Kowalski', max_length=60),
            preserve_default=False,
        ),
    ]
